<?php

namespace Database\Seeders;

use App\Models\AboutHighlight;
use App\Models\Article;
use App\Models\EnterpriseService;
use App\Models\Partner;
use App\Models\Publication;
use App\Models\ResearchDomain;
use App\Models\ResearchMetric;
use App\Models\ResearchProject;
use App\Models\SiteSetting;
use App\Models\UpcomingEvent;
use Illuminate\Database\Seeder;

class LandingPageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 1. Research Metrics
        $metrics = [
            [
                'value' => '50+',
                'label' => 'Research Projects',
                'description' => 'Completed & Active Industrial Tracks',
                'order' => 1,
            ],
            [
                'value' => '30+',
                'label' => 'Industrial Applications',
                'description' => 'Tested in Real-World Environments',
                'order' => 2,
            ],
            [
                'value' => '20+',
                'label' => 'Strategic Partners',
                'description' => 'Global & National Collaborators',
                'order' => 3,
            ],
            [
                'value' => '15+',
                'label' => 'Principal Researchers',
                'description' => 'And Interdisciplinary Fellows',
                'order' => 4,
            ],
        ];
        foreach ($metrics as $metric) {
            ResearchMetric::updateOrCreate(['label' => $metric['label']], $metric);
        }

        // 2. About Highlights
        $highlights = [
            [
                'icon' => 'Cpu',
                'title' => 'Applied R&D',
                'description' => 'Translating theoretical breakthroughs into scalable, industrially hardened solutions across Southeast Asia.',
                'order' => 1,
            ],
            [
                'icon' => 'Network',
                'title' => 'Industry Integration',
                'description' => 'Bridging academic laboratory research with direct manufacturing execution systems and real-world deployment.',
                'order' => 2,
            ],
            [
                'icon' => 'Users',
                'title' => 'Capacity Building',
                'description' => 'Training next-generation engineers, data scientists, and executive industrial leaders.',
                'order' => 3,
            ],
            [
                'icon' => 'Leaf',
                'title' => 'Sustainable Impact',
                'description' => 'Targeting measurable net-zero decarbonization, energy efficiency, and ESG circularity metrics.',
                'order' => 4,
            ],
        ];
        foreach ($highlights as $hl) {
            AboutHighlight::updateOrCreate(['title' => $hl['title']], $hl);
        }

        // 3. Research Domains
        $domains = [
            [
                'domain_number' => '01 / DOMAIN',
                'title' => 'Sustainable Technology & Green Systems',
                'title_id' => 'Teknologi Berkelanjutan & Sistem Hijau',
                'slug' => 'sustainable-tech-green-systems',
                'icon' => 'Leaf',
                'summary' => 'Eco-efficiency frameworks, carbon lifecycle analysis, and circular materials development.',
                'summary_id' => 'Kerangka eko-efisiensi, analisis siklus hidup karbon, dan material sirkular.',
                'focus_areas' => ['Eco-efficiency Frameworks', 'Carbon Lifecycle Analysis', 'Circular Materials'],
                'lead_researcher' => 'Dr. Ir. Wahyu H., M.T.',
                'link' => '#',
                'order' => 1,
                'is_active' => true,
            ],
            [
                'domain_number' => '02 / DOMAIN',
                'title' => 'Smart Manufacturing & Industry 4.0',
                'title_id' => 'Manufaktur Cerdas & Industri 4.0',
                'slug' => 'smart-manufacturing-industry-4',
                'icon' => 'Cpu',
                'summary' => 'Cyber-physical systems, autonomous robotics, digital shopfloors, and intelligent MES architectures.',
                'summary_id' => 'Sistem siber-fisik, robotika otonom, lantai pabrik digital, dan arsitektur MES cerdas.',
                'focus_areas' => ['Cyber-Physical Systems', 'Autonomous Robotics', 'Digital Shopfloors', 'Intelligent MES'],
                'lead_researcher' => 'Prof. Dr. Agus S., S.T., M.T.',
                'link' => '#',
                'order' => 2,
                'is_active' => true,
            ],
            [
                'domain_number' => '03 / DOMAIN',
                'title' => 'Supply Chain & Logistics Optimization',
                'title_id' => 'Optimasi Rantai Pasok & Logistik',
                'slug' => 'supply-chain-logistics-optimization',
                'icon' => 'Truck',
                'summary' => 'Predictive logistics networks, maritime routing, inventory digital twins, and resilient sourcing models.',
                'summary_id' => 'Jaringan logistik prediktif, rute maritim, digital twin inventaris, dan pasokan tangguh.',
                'focus_areas' => ['Predictive Logistics', 'Maritime Routing', 'Digital Twins', 'Resilient Sourcing'],
                'lead_researcher' => 'Dr. Budi Santoso, M.Sc.',
                'link' => '#',
                'order' => 3,
                'is_active' => true,
            ],
            [
                'domain_number' => '04 / DOMAIN',
                'title' => 'Applied Data Science & Industrial AI',
                'title_id' => 'Sains Data Terapan & AI Industri',
                'slug' => 'applied-data-science-industrial-ai',
                'icon' => 'Brain',
                'summary' => 'Physics-informed neural networks, computer vision quality assurance, and edge AI telemetry.',
                'summary_id' => 'Jaringan saraf berbasis fisika, computer vision penjaminan mutu, dan telemetri edge AI.',
                'focus_areas' => ['Physics-Informed NNs', 'Computer Vision QA', 'Edge AI Telemetry'],
                'lead_researcher' => 'Dr. Dedi Kurniawan, S.Si., M.Kom.',
                'link' => '#',
                'order' => 4,
                'is_active' => true,
            ],
            [
                'domain_number' => '05 / DOMAIN',
                'title' => 'Environmental Tech & Circular Economy',
                'title_id' => 'Teknologi Lingkungan & Ekonomi Sirkular',
                'slug' => 'environmental-tech-circular-economy',
                'icon' => 'Recycle',
                'summary' => 'Industrial waste upcycling, bio-reactor wastewater treatment, and secondary resource harvesting.',
                'summary_id' => 'Upcycling limbah industri, pengolahan air limbah bio-reaktor, dan pemanfaatan sumber daya sekunder.',
                'focus_areas' => ['Waste Upcycling', 'Bio-reactor Treatment', 'Secondary Resources'],
                'lead_researcher' => 'Dr. Rina Novita, S.T., M.Eng.',
                'link' => '#',
                'order' => 5,
                'is_active' => true,
            ],
            [
                'domain_number' => '06 / DOMAIN',
                'title' => 'Renewable Energy & Smart Grid Systems',
                'title_id' => 'Energi Terbarukan & Sistem Smart Grid',
                'slug' => 'renewable-energy-smart-grid',
                'icon' => 'Zap',
                'summary' => 'Microgrid scheduling, battery energy storage analytics, and decentralized green power management.',
                'summary_id' => 'Penjadwalan microgrid, analitik baterai penyimpan energi, dan pengelolaan energi bersih terdesentralisasi.',
                'focus_areas' => ['Microgrid Scheduling', 'BESS Analytics', 'Decentralized Clean Energy'],
                'lead_researcher' => 'Dr. Ir. Ahmad Fauzi, M.T.',
                'link' => '#',
                'order' => 6,
                'is_active' => true,
            ],
            [
                'domain_number' => '07 / DOMAIN',
                'title' => 'Applied Ergonomics & Human Factors',
                'title_id' => 'Ergonomi Terapan & Faktor Manusia',
                'slug' => 'applied-ergonomics-human-factors',
                'icon' => 'UserCheck',
                'summary' => 'Human-machine interfaces, cognitive workload assessment, worker ergonomics, and occupational safety.',
                'summary_id' => 'Antarmuka manusia-mesin, asesmen beban kerja kognitif, ergonomi pekerja, dan keselamatan kerja.',
                'focus_areas' => ['Human-Machine Interfaces', 'Cognitive Workload', 'Worker Ergonomics', 'Safety 4.0'],
                'lead_researcher' => 'Dr. Maya Indriani, S.T., M.T.',
                'link' => '#',
                'order' => 7,
                'is_active' => true,
            ],
            [
                'domain_number' => '08 / DOMAIN',
                'title' => 'Industrial Automation & Digitalization',
                'title_id' => 'Otomasi & Digitalisasi Industri',
                'slug' => 'industrial-automation-digitalization',
                'icon' => 'Sliders',
                'summary' => 'PLC integration, SCADA telemetry, industrial IoT sensor meshes, and process automation.',
                'summary_id' => 'Integrasi PLC, telemetri SCADA, jaringan sensor IoT industri, dan otomatisasi proses.',
                'focus_areas' => ['PLC Integration', 'SCADA Telemetry', 'IIoT Meshes', 'Process Automation'],
                'lead_researcher' => 'Dr. Hendra Gunawan, S.T., M.T.',
                'link' => '#',
                'order' => 8,
                'is_active' => true,
            ],
        ];
        foreach ($domains as $domain) {
            ResearchDomain::updateOrCreate(['slug' => $domain['slug']], $domain);
        }

        // 4. Featured Research Projects
        $projects = [
            [
                'category' => 'Supply Chain',
                'category_tag' => 'AI & LOGISTICS',
                'title' => 'Autonomous Fleet Logistics & Predictive Cost Optimization',
                'title_id' => 'Logistik Armada Otonom & Optimasi Biaya Prediktif',
                'slug' => 'autonomous-fleet-logistics',
                'image_url' => 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80',
                'lead_researcher' => 'Dr. Ir. Hendra S.',
                'summary' => 'Integrated optimization framework combining routing heuristics and deep reinforcement learning for high-density metropolitan delivery networks.',
                'summary_id' => 'Kerangka kerja optimasi terintegrasi yang menggabungkan heuristik perutean dan deep reinforcement learning untuk jaringan pengiriman metropolitan berkepadatan tinggi.',
                'tech_stack' => ['Deep RL', 'Routing Heuristics', 'Fleet Telemetry', 'Cost Optimization'],
                'case_study_url' => '#project-autonomous-fleet-logistics',
                'funding_source' => 'DIKTI Matching Fund & Transtrack',
                'start_year' => 2025,
                'end_year' => 2026,
                'featured' => true,
                'is_active' => true,
                'order' => 1,
            ],
            [
                'category' => 'Sustainable Energy',
                'category_tag' => 'RENEWABLE ENERGY',
                'title' => 'AI-Driven Smart Microgrid Management for Distributed Rural Infrastructure',
                'title_id' => 'Manajemen Smart Microgrid Berbasis AI untuk Infrastruktur Pedesaan Terdistribusi',
                'slug' => 'smart-microgrid-management',
                'image_url' => 'https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=800&q=80',
                'lead_researcher' => 'Prof. Dr. Siti Rahmawati, S.T., M.T.',
                'summary' => 'Decentralized control algorithms predicting renewable variability and orchestrating hybrid storage dispatch across remote island clusters.',
                'summary_id' => 'Algoritma kontrol terdesentralisasi yang memprediksi variabilitas energi terbarukan dan mengatur alokasi penyimpanan hibrida di klaster pulau terpencil.',
                'tech_stack' => ['Microgrid AI', 'BESS Dispatch', 'Renewable Forecasting', 'IoT Telemetry'],
                'case_study_url' => '#project-smart-microgrid-management',
                'funding_source' => 'LPDP National Priority Research Grant',
                'start_year' => 2024,
                'end_year' => 2026,
                'featured' => true,
                'is_active' => true,
                'order' => 2,
            ],
            [
                'category' => 'Smart Manufacturing',
                'category_tag' => 'SMART FACTORY',
                'title' => 'Digital Twin Implementation for Sustainable Textile Manufacturing',
                'title_id' => 'Implementasi Digital Twin untuk Manufaktur Tekstil Berkelanjutan',
                'slug' => 'digital-twin-textile',
                'image_url' => 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
                'lead_researcher' => 'Dr. Agung P. W., M.Eng.',
                'summary' => 'Physics-guided deep learning models delivering real-time energy profiling, fiber defect detection, and automated loom parameter adjustments.',
                'summary_id' => 'Model deep learning terpandu fisika yang menghadirkan profil energi waktu nyata, deteksi cacat serat, dan penyesuaian otomatis parameter alat tenun.',
                'tech_stack' => ['Digital Twin', 'Computer Vision', 'Edge AI', 'Industrial IoT'],
                'case_study_url' => '#project-digital-twin-textile',
                'funding_source' => 'Kemenperin Industrial Innovation Fund',
                'start_year' => 2025,
                'end_year' => 2027,
                'featured' => true,
                'is_active' => true,
                'order' => 3,
            ],
        ];
        foreach ($projects as $proj) {
            ResearchProject::updateOrCreate(['slug' => $proj['slug']], $proj);
        }

        // 5. Academic Publications
        $publications = [
            [
                'badge' => 'Journal Paper (Q1)',
                'badge_type' => 'green',
                'quartile' => 'Q1',
                'indexing' => 'IEEE Xplore / Scopus Q1',
                'domain_tag' => 'Sustainable Energy',
                'year' => 2026,
                'venue' => 'IEEE Transactions on Sustainable Energy',
                'doi' => 'DOI: 10.1109/TSTE.2026.14209',
                'title' => 'Decentralized Energy Scheduling in Hybrid Microgrids Using Multi-Agent Reinforcement Learning',
                'title_id' => 'Penjadwalan Energi Terdesentralisasi pada Microgrid Hibrida Menggunakan Pembelajaran Penguatan Multi-Agen',
                'abstract' => 'This paper presents a decentralized scheduling strategy using multi-agent deep reinforcement learning for islanded hybrid microgrids subjected to high renewable penetration.',
                'abstract_id' => 'Makalah ini menyajikan strategi penjadwalan terdesentralisasi menggunakan pembelajaran penguatan multi-agen untuk microgrid hibrida terisolasi dengan penetrasi energi terbarukan tinggi.',
                'authors' => 'Rahmawati, S., Hendra, S., Pratama, A., & Chen, W.',
                'pdf_url' => '#',
                'doi_url' => 'https://doi.org/10.1109/TSTE.2026.14209',
                'citation_count' => 14,
                'is_featured' => true,
                'is_active' => true,
                'order' => 1,
            ],
            [
                'badge' => 'Conference Paper',
                'badge_type' => 'gray',
                'quartile' => 'Scopus',
                'indexing' => 'Scopus / IEOM',
                'domain_tag' => 'Smart Manufacturing',
                'year' => 2025,
                'venue' => 'Proc. 15th Int. Conf. on Industrial Engineering & Operations Management',
                'doi' => 'DOI: 10.1016/j.cie.2025.10982',
                'title' => 'Real-Time Defect Detection in High-Speed Textile Manufacturing Using Edge AI',
                'title_id' => 'Deteksi Cacat Waktu Nyata pada Manufaktur Tekstil Berkecepatan Tinggi Menggunakan Edge AI',
                'abstract' => 'An edge computing pipeline integrating lightweight convolutional networks with FPGA hardware accelerators for sub-millisecond yarn defect classification.',
                'abstract_id' => 'Pipeline komputasi edge yang mengintegrasikan convolutional networks ringan dengan akselerator perangkat keras FPGA untuk klasifikasi cacat benang sub-milidetik.',
                'authors' => 'Agung, P. W., Wijaya, B., & Setiawan, R.',
                'pdf_url' => '#',
                'doi_url' => 'https://doi.org/10.1016/j.cie.2025.10982',
                'citation_count' => 8,
                'is_featured' => true,
                'is_active' => true,
                'order' => 2,
            ],
            [
                'badge' => 'Journal Paper (Q1)',
                'badge_type' => 'green',
                'quartile' => 'Q1',
                'indexing' => 'Elsevier / Scopus Q1 / WoS',
                'domain_tag' => 'Circular Economy',
                'year' => 2025,
                'venue' => 'Journal of Cleaner Production',
                'doi' => 'DOI: 10.1016/j.jclepro.2025.14120',
                'title' => 'Modular Bio-reactor System for High-Yield Industrial Wastewater Treatment',
                'title_id' => 'Sistem Bio-reaktor Modular untuk Pengolahan Air Limbah Industri Berdaya Hasil Tinggi',
                'abstract' => 'Comprehensive evaluation of a closed-loop catalytic bio-reactor reducing COD levels by 94.2% while recovering high-purity secondary copper precipitates.',
                'abstract_id' => 'Evaluasi komprehensif dari bio-reaktor katalitik loop tertutup yang menurunkan kadar COD sebesar 94,2% sekaligus memulihkan endapan tembaga sekunder kemurnian tinggi.',
                'authors' => 'Kurniawan, D., Lestari, M., & Nurhadi, T.',
                'pdf_url' => '#',
                'doi_url' => 'https://doi.org/10.1016/j.jclepro.2025.14120',
                'citation_count' => 22,
                'is_featured' => true,
                'is_active' => true,
                'order' => 3,
            ],
        ];
        foreach ($publications as $pub) {
            Publication::updateOrCreate(['doi' => $pub['doi']], $pub);
        }

        // 6. Enterprise Services
        $services = [
            [
                'service_number' => '01',
                'title' => 'Custom Industrial R&D',
                'title_id' => 'R&D Industri Kustom',
                'summary' => 'Tailored engineering research, prototype development, and technical validation for complex manufacturing challenges.',
                'summary_id' => 'Riset rekayasa khusus, pengembangan prototipe, dan validasi teknis untuk tantangan manufaktur yang kompleks.',
                'icon' => 'FlaskConical',
                'action_label' => 'Explore Service',
                'action_label_id' => 'Pelajari Layanan',
                'features' => ['Rapid Prototyping', 'Hardware-in-the-Loop', 'Technical Validation'],
                'target_industry' => 'Automotive & Heavy Manufacturing',
                'lead_advisor' => 'Dr. Ir. Hendra S.',
                'link' => '#contact',
                'is_featured' => true,
                'is_active' => true,
                'order' => 1,
            ],
            [
                'service_number' => '02',
                'title' => 'Supply Chain Advisory',
                'title_id' => 'Konsultasi Rantai Pasok',
                'summary' => 'End-to-end network optimization, logistics decarbonization roadmaps, and digital inventory transformation.',
                'summary_id' => 'Optimasi jaringan menyeluruh, peta jalan dekarbonisasi logistik, dan transformasi inventaris digital.',
                'icon' => 'TrendingUp',
                'action_label' => 'Explore Service',
                'action_label_id' => 'Pelajari Layanan',
                'features' => ['Fleet Route Optimization', 'Green Logistics Audits', 'Digital Twin Warehousing'],
                'target_industry' => 'Logistics, FMCG & Retail',
                'lead_advisor' => 'Dr. Maya Indriani, S.T., M.T.',
                'link' => '#contact',
                'is_featured' => true,
                'is_active' => true,
                'order' => 2,
            ],
            [
                'service_number' => '03',
                'title' => 'Lab Testing & Validation',
                'title_id' => 'Pengujian & Validasi Lab',
                'summary' => 'Certified industrial simulation, material durability stress testing, and IoT sensor benchmarking protocols.',
                'summary_id' => 'Simulasi industri bersertifikasi, uji ketahanan material, dan protokol benchmarking sensor IoT.',
                'icon' => 'CheckCircle',
                'action_label' => 'Explore Service',
                'action_label_id' => 'Pelajari Layanan',
                'features' => ['Material Stress Testing', 'IoT Benchmarking', 'Vibration & Thermal Simulation'],
                'target_industry' => 'Electronics & Energy Storage',
                'lead_advisor' => 'Dr. Hendra Gunawan, S.T., M.T.',
                'link' => '#contact',
                'is_featured' => true,
                'is_active' => true,
                'order' => 3,
            ],
            [
                'service_number' => '04',
                'title' => 'ESG & Carbon Audits',
                'title_id' => 'Audit Karbon & ESG',
                'summary' => 'Comprehensive Scope 1-3 GHG accounting, life cycle assessments (LCA), and circularity transition roadmaps.',
                'summary_id' => 'Penghitungan GRK Cakupan 1-3 yang komprehensif, analisis siklus hidup (LCA), dan peta jalan transisi sirkularitas.',
                'icon' => 'ShieldCheck',
                'action_label' => 'Explore Service',
                'action_label_id' => 'Pelajari Layanan',
                'features' => ['Scope 1-3 GHG Accounting', 'ISO 14040 Life Cycle Assessment', 'Circularity Certification'],
                'target_industry' => 'Textile, Mining & Utilities',
                'lead_advisor' => 'Dr. Rina Novita, S.T., M.Eng.',
                'link' => '#contact',
                'is_featured' => true,
                'is_active' => true,
                'order' => 4,
            ],
            [
                'service_number' => '05',
                'title' => 'Executive Talent Training',
                'title_id' => 'Pelatihan Talenta Eksekutif',
                'summary' => 'Custom corporate bootcamps in Industrial AI, Lean Operations 4.0, and sustainable systems management.',
                'summary_id' => 'Bootcamp korporat khusus dalam AI Industri, Operasi Lean 4.0, dan manajemen sistem berkelanjutan.',
                'icon' => 'Award',
                'action_label' => 'Explore Service',
                'action_label_id' => 'Pelajari Layanan',
                'features' => ['Corporate AI Bootcamps', 'Six Sigma Lean Masterclass', 'Smart Factory Workshops'],
                'target_industry' => 'State-Owned Enterprises & Corporates',
                'lead_advisor' => 'Prof. Dr. Siti Rahmawati, S.T., M.T.',
                'link' => '#contact',
                'is_featured' => true,
                'is_active' => true,
                'order' => 5,
            ],
            [
                'service_number' => '06',
                'title' => 'Technology Commercialization',
                'title_id' => 'Komersialisasi Teknologi',
                'summary' => 'IP licensing, patent valorization, technology transfer, and joint venture spin-off incubation support.',
                'summary_id' => 'Lisensi HKI, valorisasi paten, transfer teknologi, dan dukungan inkubasi spin-off joint venture.',
                'icon' => 'Layers',
                'action_label' => 'Explore Service',
                'action_label_id' => 'Pelajari Layanan',
                'features' => ['Patent Valorization', 'Technology Readiness Level (TRL) 7-9', 'Spin-off Incubation'],
                'target_industry' => 'Tech Startups & Venture Capital',
                'lead_advisor' => 'Dr. Agung P. W., M.Eng.',
                'link' => '#contact',
                'is_featured' => true,
                'is_active' => true,
                'order' => 6,
            ],
        ];
        foreach ($services as $srv) {
            EnterpriseService::updateOrCreate(['service_number' => $srv['service_number']], $srv);
        }

        // 7. Partners & Industrial Alliances
        $partners = [
            [
                'name' => 'PT PINDAD',
                'category' => 'SOE',
                'partnership_type' => 'Defense & Heavy Manufacturing R&D',
                'description' => 'Joint development of precision engineering, industrial defense hardware telemetry, and advanced materials prototyping.',
                'description_id' => 'Pengembangan bersama rekayasa presisi, telemetri perangkat keras industri pertahanan, dan prototipe material maju.',
                'logo_text' => 'PT PINDAD',
                'logo_url' => '/assets/images/partners/collegue_pindad.png',
                'website_url' => 'https://pindad.com',
                'established_year' => 2024,
                'is_featured' => true,
                'is_active' => true,
                'order' => 1,
            ],
            [
                'name' => 'BIO FARMA',
                'category' => 'SOE',
                'partnership_type' => 'Cold-Chain Logistics & Bio-Reactors',
                'description' => 'Smart cold-chain vaccine logistics optimization, bio-reactor wastewater monitoring, and ESG pharmaceutical audits.',
                'description_id' => 'Optimasi logistik rantai dingin vaksin cerdas, pemantauan air limbah bio-reaktor, dan audit ESG farmasi.',
                'logo_text' => 'BIO FARMA',
                'logo_url' => '/assets/images/partners/collegue_biofarma.png',
                'website_url' => 'https://biofarma.co.id',
                'established_year' => 2024,
                'is_featured' => true,
                'is_active' => true,
                'order' => 2,
            ],
            [
                'name' => 'BANDUNG TECHNO PARK',
                'category' => 'Technology',
                'partnership_type' => 'Tech Transfer & Startup Incubation',
                'description' => 'Commercialization platform, spin-off startup incubation, intellectual property patent valorization, and prototyping labs.',
                'description_id' => 'Platform komersialisasi teknologi, inkubasi startup spin-off, valorisasi paten HKI, dan laboratorium prototipe.',
                'logo_text' => 'BANDUNG TECHNO PARK',
                'logo_url' => '/assets/images/partners/collegue_btp.png',
                'website_url' => 'https://btp.or.id',
                'established_year' => 2023,
                'is_featured' => true,
                'is_active' => true,
                'order' => 3,
            ],
            [
                'name' => 'TRANSTRACK',
                'category' => 'Industry',
                'partnership_type' => 'Fleet Telemetry & Logistics Matching Fund',
                'description' => 'Collaborative research on deep reinforcement learning for urban delivery routes and IoT edge fleet telematics.',
                'description_id' => 'Riset kolaboratif deep reinforcement learning untuk rute pengiriman perkotaan dan telematika armada IoT edge.',
                'logo_text' => 'TRANSTRACK',
                'logo_url' => '/assets/images/partners/collegue_transtrack.png',
                'website_url' => 'https://transtrack.id',
                'established_year' => 2025,
                'is_featured' => true,
                'is_active' => true,
                'order' => 4,
            ],
            [
                'name' => 'ASYCS',
                'category' => 'Technology',
                'partnership_type' => 'Industrial AI & Systems Architecture',
                'description' => 'Smart manufacturing digital twins, high-speed computer vision quality assurance, and MES control systems integration.',
                'description_id' => 'Digital twin manufaktur cerdas, penjaminan mutu computer vision kecepatan tinggi, dan integrasi sistem kendali MES.',
                'logo_text' => 'ASYCS',
                'logo_url' => '/assets/images/partners/collegue_asycs.png',
                'website_url' => 'https://asycs.com',
                'established_year' => 2025,
                'is_featured' => true,
                'is_active' => true,
                'order' => 5,
            ],
            [
                'name' => 'TELKOM UNIVERSITY',
                'category' => 'Academic',
                'partnership_type' => 'Institutional Parent & Research Infrastructure',
                'description' => 'Host university providing world-class laboratory facilities, academic faculty researchers, and student talent pipelines.',
                'description_id' => 'Universitas induk yang menyediakan fasilitas laboratorium kelas dunia, peneliti dosen, dan jalur talenta mahasiswa.',
                'logo_text' => 'TELKOM UNIVERSITY',
                'logo_url' => '/assets/images/telu.png',
                'website_url' => 'https://telkomuniversity.ac.id',
                'established_year' => 2022,
                'is_featured' => true,
                'is_active' => true,
                'order' => 6,
            ],
        ];
        Partner::truncate();
        foreach ($partners as $ptr) {
            Partner::create($ptr);
        }

        // 8. Articles
        $articles = [
            [
                'tag' => 'STRATEGIC GRANT',
                'date' => 'SEP 10 - 2026',
                'title' => 'STAS-RG Secures Major Grant for Green Electric Transportation Energy Hubs',
                'title_id' => 'STAS-RG Raih Hibah Riset Rp 8.5 Miliar untuk Pengembangan Hub Energi Transportasi Listrik Hijau',
                'slug' => 'stas-rg-secures-grant-green-transport',
                'summary' => 'National research consortium awards IDR 8.5B to develop smart charging networks with integrated battery swapping telemetry and edge AI optimization.',
                'summary_id' => 'Konsorsium riset nasional memberikan pendanaan Rp 8,5 Miliar untuk pengembangan jaringan pengisian daya cerdas terintegrasi telemetri penukaran baterai dan AI edge.',
                'content' => "CoE STAS-RG has officially been awarded an IDR 8.5 Billion competitive grant by the National Industrial Decarbonization Taskforce to deploy next-generation green transportation infrastructure.\n\nThe project integrates decentralized smart microgrid storage with predictive battery swapping telemetry across 40 prototype metropolitan hubs in Bandung and Jakarta. Lead investigator Dr. Ir. Hendra S. stated that the solution will cut peak electricity charging strain by 38% while enabling zero-emission urban fleets.",
                'content_id' => "CoE STAS-RG secara resmi meraih pendanaan hibah kompetitif nasional sebesar Rp 8,5 Miliar dari Satgas Dekarbonisasi Industri Nasional untuk membangun infrastruktur transportasi hijau generasi berikutnya.\n\nProyek ini mengintegrasikan penyimpanan microgrid cerdas terdesentralisasi dengan telemetri prediktif penukaran baterai di 40 hub prototipe perkotaan di Bandung dan Jakarta. Peneliti utama Dr. Ir. Hendra S. menyampaikan bahwa solusi ini akan mengurangi beban puncak pengisian daya listrik sebesar 38% serta mempercepat transisi armada logistik bebas emisi.",
                'author' => 'Dr. Ir. Hendra S. & Media Center STAS-RG',
                'image_url' => '/assets/images/research/autonomous_fleet.png',
                'read_time' => '4 min read',
                'external_url' => 'https://telkomuniversity.ac.id/research-news',
                'is_featured' => true,
                'is_active' => true,
                'order' => 1,
            ],
            [
                'tag' => 'RESEARCH REPORT',
                'date' => 'AUG 28 - 2026',
                'title' => 'Policy Report: Resilient Supply Chains & Decarbonization in Indonesian MSMEs',
                'title_id' => 'Laporan Kebijakan: Rantai Pasok Tangguh & Dekarbonisasi Manufaktur UKM Indonesia',
                'slug' => 'policy-report-resilient-supply-chains',
                'summary' => 'Comprehensive study provides policy recommendations for integrating circular logistics standards and Scope 3 carbon tracking across West Java manufacturers.',
                'summary_id' => 'Studi komprehensif menyajikan rekomendasi kebijakan integrasi standar logistik sirkular dan pelacakan jejak karbon Scope 3 bagi industri manufaktur Jawa Barat.',
                'content' => "The Center of Excellence for Sustainable Technology & Applied Sciences (CoE STAS-RG) has published its flagship 2026 Industrial Policy Whitepaper on Sustainable Manufacturing Resilience.\n\nCovering over 120 medium manufacturing facilities, the research highlights how adopting edge AI monitoring and multi-echelon inventory optimization reduced material waste by 24% while meeting stringent international ESG export requirements.",
                'content_id' => "Center of Excellence for Sustainable Technology & Applied Sciences (CoE STAS-RG) menerbitkan Laporan Kebijakan Industri Unggulan 2026 tentang Ketahanan Manufaktur Berkelanjutan.\n\nMelibatkan lebih dari 120 fasilitas manufaktur menengah, riset ini menyoroti bagaimana penerapan pemantauan Edge AI dan optimasi inventaris multi-eselon berhasil menurunkan limbah material sebesar 24% sekaligus memenuhi standar kepatuhan ekspor ESG internasional.",
                'author' => 'Prof. Dr. Ir. Adiwijaya, S.Si., M.Si. & Tim Riset',
                'image_url' => '/assets/images/research/digital_twin.png',
                'read_time' => '6 min read',
                'external_url' => 'https://telkomuniversity.ac.id/publications',
                'is_featured' => true,
                'is_active' => true,
                'order' => 2,
            ],
            [
                'tag' => 'ACADEMIC EVENT',
                'date' => 'JUL 15 - 2026',
                'title' => 'Telkom University Researchers Win Best Paper at International Applied Science Symposium',
                'title_id' => 'Peneliti STAS-RG Raih Penghargaan Best Paper di Simposium Internasional Sains Terapan 2026',
                'slug' => 'telkom-university-researchers-win-best-paper',
                'summary' => 'CoE STAS-RG faculty awarded best technical presentation for multi-agent reinforcement learning optimization in remote island microgrid clusters.',
                'summary_id' => 'Dosen dan peneliti CoE STAS-RG dianugerahi presentasi teknis terbaik untuk riset optimasi multi-agent reinforcement learning pada klaster microgrid kepulauan.',
                'content' => "At the 15th International Symposium on Sustainable Energy & Industrial Cyber-Physical Systems, the research paper presented by Prof. Dr. Siti Rahmawati and the STAS-RG team received the prestigious Best Paper Award.\n\nThe evaluated algorithm demonstrated 99.4% stability under extreme intermittent solar irradiance and storm conditions in pilot trials across the Thousand Islands cluster.",
                'content_id' => "Pada Simposium Internasional ke-15 tentang Energi Berkelanjutan & Sistem Siber-Fisik Industri, makalah riset yang dipresentasikan oleh Prof. Dr. Siti Rahmawati bersama tim STAS-RG berhasil meraih Penghargaan Makalah Terbaik (Best Paper Award).\n\nAlgoritma yang diuji menunjukkan stabilitas 99,4% di bawah fluktuasi cuaca ekstrem dan badai dalam uji coba percontohan di klaster Kepulauan Seribu.",
                'author' => 'Prof. Dr. Siti Rahmawati & Chen, W.',
                'image_url' => '/assets/images/research/smart_microgrid.png',
                'read_time' => '3 min read',
                'external_url' => 'https://doi.org/10.1109/TSTE.2026.14209',
                'is_featured' => false,
                'is_active' => true,
                'order' => 3,
            ],
        ];
        foreach ($articles as $art) {
            Article::updateOrCreate(['slug' => $art['slug']], $art);
        }

        // 9. Events (Symposia, Masterclasses & Workshops)
        $events = [
            [
                'tag' => 'UPCOMING SYMPOSIUM',
                'date_display' => '24-25 OKT 2026',
                'time_display' => '08:30 - 17:00 WIB',
                'title' => 'International Symposium on Sustainable Technology & Smart Systems (IS-STSS 2026)',
                'title_id' => 'Simposium Internasional Teknologi Berkelanjutan & Sistem Cerdas (IS-STSS 2026)',
                'description' => 'Join world-renowned researchers, industrial engineering executives, and policymakers for keynote tracks on decarbonization, smart manufacturing, and AI telemetry architectures.',
                'description_id' => 'Berinteraksi langsung dengan para ilmuwan terkemuka dunia, praktisi rekayasa manufaktur, dan perumus kebijakan dalam sesi pleno dekarbonisasi industri, manufaktur cerdas, dan arsitektur telemetri AI.',
                'speaker_name' => 'Prof. Dr. Ir. Adiwijaya, S.Si., M.Si.',
                'speaker_title' => 'Lead Advisor & Research Center Director, Telkom University',
                'location' => 'Auditorium Gd. Damar (Lt. 2) / Hybrid Zoom Streaming',
                'registration_link' => '#contact',
                'brochure_url' => 'https://telkomuniversity.ac.id/is-stss-2026',
                'image_url' => '/assets/images/research/digital_twin.png',
                'quota_text' => 'Terbuka untuk 150 Peserta / Early Bird Aktif',
                'primary_action_text' => 'Daftar Simposium',
                'secondary_action_text' => 'Unduh Jadwal & TOR',
                'is_featured' => true,
                'is_active' => true,
                'order' => 1,
                'event_date' => '2026-10-24',
            ],
            [
                'tag' => 'HANDS-ON WORKSHOP',
                'date_display' => '05-06 NOV 2026',
                'time_display' => '09:00 - 16:30 WIB',
                'title' => 'Hands-on Masterclass: Industrial IoT & Real-Time Energy Telemetry Architectures',
                'title_id' => 'Masterclass Praktis: IoT Industri & Arsitektur Telemetri Energi Waktu Nyata',
                'description' => 'Intensive 2-day technical lab workshop for practicing engineers covering edge microcontroller telemetry, MQTT microgrid pipelines, and Grafana dashboard integration.',
                'description_id' => 'Workshop teknis intensif 2 hari di laboratorium riset untuk praktisi industri mencakup integrasi mikrokontroler edge, pipeline MQTT microgrid, dan visualisasi dasbor analitik Grafana.',
                'speaker_name' => 'Dr. Ir. Hendra S., S.T., M.T.',
                'speaker_title' => 'Head of IoT Embedded Systems & Automation Lab',
                'location' => 'Laboratorium Sistem Tertanam IoT, Gd. Riset Terpadu Lt. 4',
                'registration_link' => '#contact',
                'brochure_url' => 'https://telkomuniversity.ac.id/workshop-iot',
                'image_url' => '/assets/images/research/smart_microgrid.png',
                'quota_text' => 'Terbatas 35 Peserta (Hands-on Hardware)',
                'primary_action_text' => 'Ikuti Masterclass',
                'secondary_action_text' => 'Silabus Lengkap',
                'is_featured' => true,
                'is_active' => true,
                'order' => 2,
                'event_date' => '2026-11-05',
            ],
            [
                'tag' => 'EXECUTIVE MASTERCLASS',
                'date_display' => '18 NOV 2026',
                'time_display' => '13:00 - 17:00 WIB',
                'title' => 'Executive Roundtable: Net-Zero Supply Chain Decarbonization & ESG Compliance',
                'title_id' => 'Roundtable Eksekutif: Dekarbonisasi Rantai Pasok Net-Zero & Kepatuhan ESG',
                'description' => 'Strategic executive briefing for supply chain directors and sustainability managers navigating carbon taxation, Scope 3 audits, and circular logistics implementation.',
                'description_id' => 'Sesi pengarahan strategis eksekutif bagi direktur rantai pasok dan manajer keberlanjutan untuk menavigasi regulasi pajak karbon, audit emisi Scope 3, dan implementasi logistik sirkular.',
                'speaker_name' => 'Prof. Dr. Siti Rahmawati & BUMN Advisory Council',
                'speaker_title' => 'Principal Investigator in Sustainable Logistics & ESG Audits',
                'location' => 'Executive Meeting Lounge, BTP & Live Private Broadcast',
                'registration_link' => '#contact',
                'brochure_url' => 'https://telkomuniversity.ac.id/esg-roundtable',
                'image_url' => '/assets/images/research/autonomous_fleet.png',
                'quota_text' => 'Khusus Pimpinan Industri & BUMN (40 Kursi)',
                'primary_action_text' => 'Reservasi Kursi Eksekutif',
                'secondary_action_text' => 'Unduh Executive Brief',
                'is_featured' => false,
                'is_active' => true,
                'order' => 3,
                'event_date' => '2026-11-18',
            ],
            [
                'tag' => 'TECHNICAL BOOTCAMP',
                'date_display' => '02-04 DES 2026',
                'time_display' => '09:00 - 15:30 WIB',
                'title' => 'National Technical Bootcamp: Edge AI for High-Speed Visual Quality Inspection',
                'title_id' => 'Bootcamp Teknis Nasional: Edge AI untuk Inspeksi Kualitas Visual Berkecepatan Tinggi',
                'description' => 'Practical engineering bootcamp focusing on deploying lightweight convolutional networks on FPGA and edge accelerators for sub-millisecond defect detection.',
                'description_id' => 'Bootcamp rekayasa praktis yang berfokus pada penerapan convolutional neural network ringan pada akselerator FPGA dan edge untuk deteksi cacat sub-milidetik pada jalur manufaktur.',
                'speaker_name' => 'Agung, P. W., M.Eng. & Tim Computer Vision',
                'speaker_title' => 'Senior Machine Learning & Computer Vision Research Fellow',
                'location' => 'Computer Vision & AI Lab, Gd. Pelatihan Telkom University',
                'registration_link' => '#contact',
                'brochure_url' => 'https://telkomuniversity.ac.id/bootcamp-ai',
                'image_url' => '/assets/images/publications/edge_ai_defect.png',
                'quota_text' => 'Terbuka untuk 50 Peneliti & Mahasiswa Lanjutan',
                'primary_action_text' => 'Daftar Bootcamp',
                'secondary_action_text' => 'Unduh Modul Pembelajaran',
                'is_featured' => false,
                'is_active' => true,
                'order' => 4,
                'event_date' => '2026-12-02',
            ],
        ];
        UpcomingEvent::truncate();
        foreach ($events as $evt) {
            UpcomingEvent::create($evt);
        }

        // 10. Site Settings
        $settings = [
            'center_name' => 'CoE STAS-RG',
            'tagline' => 'Advancing Sustainable Technology Through Research & Innovation',
            'institution' => 'Telkom University',
            'sub_institution' => 'Center of Excellence',
            'director_quote' => 'Pioneering sustainable technology with impact. We build solutions that scale beyond laboratories.',
            'director_name' => 'Prof. Dr. Ir. Adiwijaya, S.Si., M.Si.',
            'director_title' => 'Lead Advisor & Research Center Director',
            'contact_email' => 'stasrg@telkomuniversity.ac.id',
            'contact_phone' => '+62 22 756 4108',
            'address' => 'Center of Excellence STAS-RG, Telkom University, Jl. Telekomunikasi No. 1, Terusan Buahbatu, Bandung, West Java 40257, Indonesia',
        ];
        foreach ($settings as $key => $value) {
            SiteSetting::updateOrCreate(['key' => $key], ['value' => $value]);
        }
    }
}
